.build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"
    - docker build --pull -t "$DOCKER_HUB_IMAGE:$CI_COMMIT_REF_NAME" .
    - docker push "$DOCKER_HUB_IMAGE:$CI_COMMIT_REF_NAME"

build-master:
  extends:
    - .build
  only:
    - master
  before_script:
    - CI_COMMIT_REF_NAME=latest

build:
  extends:
    - .build
  only:
    - develop
    - tags
  except:
    - master
