stages:
  - build
  - deploy

.build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"
    - docker tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME" "$DOCKER_HUB_IMAGE:$CI_COMMIT_REF_NAME"
    - docker push "$DOCKER_HUB_IMAGE:$CI_COMMIT_REF_NAME"

build-master:
  extends:
    - .build
  only:
    - master
  before_script:
    - CI_COMMIT_REF_NAME=latest

build:
  extends:
    - .build
  only:
    - develop
    - tags
  except:
    - master

deploy:
  stage: deploy
  needs:
    - build
  only:
    - /^[0-9]+\.[0-9]+\.[0-9]+$/
  except:
    - branches
  image: kroniak/ssh-client
  script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh $SSH_USERNAME@$SSH_SERVER_IP -p $SSH_PORT "kubectl set image deployments/vision vision=$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME --record"
