image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"

build-master:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
    - docker build --pull -t "$DOCKER_HUB_IMAGE" .
    - docker push "$DOCKER_HUB_IMAGE"
  only:
    - master

build:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master

build-hub:
  stage: build
  script:
    - docker build --pull -t "$DOCKER_HUB_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$DOCKER_HUB_IMAGE:$CI_COMMIT_REF_SLUG"
  only:
    - tags
